### PR TITLE
Clarify math for bucket limit chance

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
I really dont like limiting this any higher than is strictly neccessary. Its ok to introduce some occasional failures, and simulation results show maps with 10k elements rarely going above 10 for a few million tries (though admittedly if 10k elements is the target may be best to switch to 11/12 as the limit).

**Comment by TheBlueMatt** [comment]
Though, indeed, I was overcomplicating the math, it is rather simple.

**Comment by TheBlueMatt** [comment]
See https://github.com/TheBlueMatt/bitcoin/commit/d359604ec3ae78da1e4406e854fb2878a1e806bb#diff-fda2dd15c676603245f3908de192102dR86

**Comment by sipa** [comment]
@TheBlueMatt Looks good. It's not a simple binomial distribution though, but a multinomial. The number entries in a single given bucket is binomially distributed, but the distribution of the highest number over all buckets does not have a simple formula. It's well approximated by multiplying the chance for a high number in one bucket by the total number of buckets.

Also, it assumes that the number of buckets is at least equal to the number of entries (which is true because std::unordered_map specifies that the default max load factor 1).

The numbers look correct.

**Pull request closed without merging**
